### ISSUE TITLE
Test cases failed in PROJ benchmark's fixed versions

### ISSUE THREAD

**Issue by MinseokJGit** [Suresoft-GLaDOS/defects4cpp#1]
I executed the 39 test cases across proj#1 to proj#13, and found that 31 of them failed in both the buggy and fixed versions (for instance, in buggy-1 and fixed-1).

I'm uncertain about these results.

Could you let me know whether I ran the test cases correctly? 

I ran the benchmark in AMD cpu.

**Comment by minhyuk** [comment]
the defects4cpp moved to "https://github.com/Suresoft-GLaDOS/bugscpp" here. can you check your issue with this latest bugscpp?
