### ISSUE TITLE
One-shot Checkout to Test

### ISSUE THREAD

**Issue by neoeva07** [Suresoft-GLaDOS/defects4cpp#5]
As a defects4cpp developer, need one-shot command 'from checkout to test' to convenient.
When I check some buggy version is valid or not, I have to type bunch of command line and waiting each command finished.
if there is some command like "checkout-build-test", maybe much convenient to check each version of defects.
and also, I will be happy if there are command which checks the fixed version of the defect was really fixed buggy version or not and check the whole cycle.

**Comment by hakumaku** [comment]
Close due to having added a feature (#12) that mitigates this difficulty.
