### ISSUE TITLE
cppcheck test is weird: test.out is empty but test result passed

### ISSUE THREAD

**Issue by gjxo12** [Suresoft-GLaDOS/defects4cpp#55]
Hello, I use cppcheck build and test to using defect4cpp

Using command
`defects4cpp/defects4cpp$ python3 d++.py checkout cppcheck 1`
`defects4cpp/defects4cpp$ python3 d++.py build cppcheck/fixed#1`
`defects4cpp/defects4cpp$ python3 d++.py test cppcheck/fixed#1`

but.. the test result is below

/cppcheck-fixed#1-2/2.out.put
`Internal ctest changing into directory: /home/workspace/build
Test project /home/workspace/build
No tests were found!!!`

is this Bug? 
Ummm.. my cppcheck/build/bin has one binary 'cppcheck'
and the command is here
`./cppcheck ../../test/`

`cppcheck: Failed to load library configuration file 'std.cfg'. File not found
nofile:0:0: information: Failed to load std.cfg. Your Cppcheck installation is broken, please re-install. The Cppcheck binary was compiled with FILESDIR set to "/usr/local/share/Cppcheck" and will therefore search for std.cfg in /usr/local/share/Cppcheck/cfg. [failedToLoadCfg]`

plz help this problem

**Comment by HansolChoe** [comment]
Resolved and closed
